version: "3.8"

services:
  server: # server
    build:
      context: . # nginx need to copy some file from ../ inside the image so we cant already specify ./dockerfiles
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # bind mount
    depends_on:
      - php
      - mysql
  php: # php interpreter
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # delegated is for performance optimization (changes are reflted in batch and not instantly)
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"] # you can add dockerfile option inside the docker-compose (but it's not recommended)
  npm:
    image: node:14
    working_dir: /var/www/html # you can add dockerfile option inside the docker-compose (but it's not recommended)
    entrypoint: ["npm"] # you can add dockerfile option inside the docker-compose (but it's not recommended)
    volumes:
      - ./src:/var/www/html
