# Build stage 1
FROM node:14-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# Build stage 2
FROM nginx:stable-alpine

# Copy from stage1 (named build) /app/build to user/share/nginx/html
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



